"""Compare our recomputed features with the precomputed dataset columns.

Run with: uv run python scripts/compare_features.py
Writes reports/feature_comparison.md.
"""

from pathlib import Path

import pandas as pd

from pawnlink.features.extract import extract_features

RAW_PATH = Path("data/raw/train.csv")
REPORT_PATH = Path("reports/feature_comparison.md")

# dataset column -> (our feature, scale applied to ours, tolerance)
PAIRS = {
    "url_length": ("url_length", 1, 0),
    "dot_count": ("num_dots", 1, 0),
    "number_of_digits": ("num_digits", 1, 0),
    "percentage_numeric_chars": ("pct_digits", 100, 0.01),
    "url_entropy": ("url_entropy", 1, 1e-6),
    "has_ip_address": ("has_ip", 1, 0),
    "https_flag": ("has_https", 1, 0),
    "path_length": ("path_length", 1, 0),
    "query_param_count": ("num_query_params", 1, 0),
    "has_hyphen_in_domain": ("has_hyphen_in_host", 1, 0),
    "domain_name_length": ("domain_length", 1, 0),
    "tld_length": ("tld_length", 1, 0),
    "subdomain_count": ("subdomain_count", 1, 0),
    "tld_popularity": ("is_popular_tld", 1, 0),
    "suspicious_file_extension": ("has_suspicious_extension", 1, 0),
}


def main() -> None:
    raw = pd.read_csv(RAW_PATH)
    ours = pd.DataFrame([extract_features(u) for u in raw["URL"]])

    rows = []
    for col, (feat, scale, tol) in PAIRS.items():
        differs = (raw[col] - ours[feat] * scale).abs() > tol
        example = raw.loc[differs, "URL"].iloc[0] if differs.any() else ""
        rows.append((col, feat, differs.mean(), example))
    rows.sort(key=lambda r: r[2], reverse=True)

    lines = [
        "# Feature comparison: dataset columns vs recomputed",
        "",
        f"Rows compared: {len(raw):,} (`{RAW_PATH}`, before dedup). "
        "Generated by `scripts/compare_features.py`.",
        "",
        "| Dataset column | Our feature | Rows that differ | Example URL |",
        "| --- | --- | ---: | --- |",
    ]
    for col, feat, rate, example in rows:
        example = f"`{example[:60]}`" if example else ""
        lines.append(f"| `{col}` | `{feat}` | {rate:.1%} | {example} |")

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines) + "\n")
    print(REPORT_PATH.read_text())


if __name__ == "__main__":
    main()
